// Unit tests for the Qwen3.5 GatedDeltaNet stateful primitives in nnml/ssm.h:
//   - nnml_ssm_conv1d_update        : depthwise causal Conv1d recurrent update
//   - nnml_ssm_gated_delta_rule_update : gated delta-rule recurrent update
//   - nnml_ssm_rms_norm_gated       : gated RMSNorm (linear-attn output norm)
//   - nnml_qwen35_partial_rotary    : partial-rotary mRoPE (full-attn layers)
//
// The expected output and expected new conv_state were generated by an
// independent numpy reference (transformers/models/qwen3_5/modeling_qwen3_5.py
// torch_causal_conv1d_update, collapsed to the decode / single-token case):
//
//   import numpy as np
//   def silu(v): return v / (1.0 + np.exp(-v))
//   rng = np.random.RandomState(20240728)
//   x     = (rng.randn(conv_dim)       * 0.7).astype(np.float32)
//   state = (rng.randn(conv_dim,kernel) * 0.5).astype(np.float32)   # last kernel inputs
//   w     = (rng.randn(conv_dim,kernel) * 0.3).astype(np.float32)
//   state2 = state.copy()
//   state2[:, :-1] = state[:, 1:]   # shift left (drop oldest, idx 0)
//   state2[:, -1]  = x              # append new at the end
//   out = silu((state2 * w).sum(axis=1)).astype(np.float32)
//
// This validates both the output AND the in-place conv_state mutation against HF.

#include <cmath>
#include <cstdio>
#include <cstring>

#include "ssm.h"
#include "tensor.h"
#include "memory.h"

// Forward-declare the scheduler's per-node dispatch entry (defined in
// nnml/src/scheduler.cpp, linked from the nnml lib). We deliberately do NOT
// include "scheduler.h" here: that header *defines* the globals `threadpool`,
// `single_graph`, `multi_graphs`, which would multi-define against the nnml
// shared library. Calling nnml_compute_node directly proves the new ops are
// reachable through the real scheduler dispatch switch (the enum case routes
// NNML_OP_SSM_CONV_UPDATE / NNML_OP_SSM_DELTA_UPDATE to the compute fns), while
// keeping the test free of the full threadpool/scheduler harness.
void nnml_compute_node(nnml_tensor * node, const nnml_compute_state * params);

static int g_fails = 0;

static const int g_conv_dim = 8;
static const int g_kernel = 4;

// Inputs (numpy RandomState 20240728). Channel-major: channel c's `kernel` taps
// are contiguous (element (tap k, channel c) at c*kernel + k). This matches the
// ggml [kernel, conv_dim] tensor layout (ne[0]=kernel, the contiguous axis), the
// GGUF ssm_conv1d.weight [kernel, conv_dim], the llm_ssm_state conv_state alloc,
// and the numpy reference (state[conv_dim, kernel], sum over the kernel axis).
static const float g_x_in[] = {
    -0.731974542f, -0.785962403f, 0.568452001f, 1.372986913f,
    -0.094989255f, -0.455060810f, 0.293488562f, 0.259672523f,
};
static const float g_state_in[] = {
    0.264919758f, 0.211291254f, 0.885799527f, 0.571287036f, -0.071123265f, 0.085200645f, 0.449657410f, 0.182596818f,
    -0.498317093f, 0.046759911f, 0.729027450f, 0.506041169f, 0.068699546f, 0.434770733f, -0.090203181f, -0.272124112f,
    0.160680100f, 0.971519291f, 1.052329659f, 0.109724000f, 0.546136498f, -0.140045986f, -0.141164109f, -0.158164412f,
    0.327550083f, 0.152249068f, 0.198634371f, -0.742488980f, -0.065642186f, 0.553287029f, 1.192807198f, -0.185929254f,
};
static const float g_w_in[] = {
    0.138578296f, -0.280673832f, 0.157998770f, 0.081310153f, 0.283548027f, 0.177000418f, 0.016698511f, -0.287809759f,
    0.200283200f, 0.244291410f, 0.575234115f, -0.195212662f, 0.668070674f, -0.053596497f, -0.313939929f, 0.305651069f,
    0.457911402f, 0.282571346f, 0.144197434f, -0.197487831f, 0.460225403f, 0.080065906f, 0.232157037f, 0.355277061f,
    0.094725728f, 0.325315297f, -0.415407360f, 0.241295144f, -0.105384834f, -0.397877902f, 0.667186499f, -0.193011448f,
};

// Expected conv_state after the in-place update (numpy state2, channel-major:
// element (k,c) at c*kernel + k, i.e. numpy state2[conv_dim, kernel] flattened).
static const float g_state_expected[] = {
    0.211291254f, 0.885799527f, 0.571287036f, -0.731974542f, 0.085200645f, 0.449657410f, 0.182596818f, -0.785962403f,
    0.046759911f, 0.729027450f, 0.506041169f, 0.568452001f, 0.434770733f, -0.090203181f, -0.272124112f, 1.372986913f,
    0.971519291f, 1.052329659f, 0.109724000f, -0.094989255f, -0.140045986f, -0.141164109f, -0.158164412f, -0.455060810f,
    0.152249068f, 0.198634371f, -0.742488980f, 0.293488562f, 0.553287029f, 1.192807198f, -0.185929254f, 0.259672523f,
};

// Expected output (numpy silu((state2 * w).sum(axis=1)), summed over the kernel axis).
static const float g_out_expected[] = {
    -0.085431613f, 0.193972051f, 0.217195868f, 0.552304804f, 0.532108068f, -0.118401088f, 0.280754805f, -0.233507261f,
};

static void check_main_update(void) {
    float state[8 * 4];
    float out[8];
    std::memcpy(state, g_state_in, sizeof(state));

    nnml_ssm_conv1d_update(g_x_in, state, g_w_in, g_conv_dim, g_kernel, out);

    // Output must match the numpy reference within f32 precision.
    for (int c = 0; c < g_conv_dim; ++c) {
        float got = out[c];
        float expv = g_out_expected[c];
        if (std::fabs(got - expv) > 1e-5f) {
            printf("FAIL out[%d]: got %.9f, expected %.9f\n", c, got, expv);
            ++g_fails;
        }
    }
    // conv_state must be mutated in place to the rolled state.
    for (int i = 0; i < g_conv_dim * g_kernel; ++i) {
        float got = state[i];
        float expv = g_state_expected[i];
        if (std::fabs(got - expv) > 1e-5f) {
            printf("FAIL conv_state[%d]: got %.9f, expected %.9f\n", i, got, expv);
            ++g_fails;
        }
    }
}

// Two consecutive updates: after update #1 the rolled state must feed update #2.
// This catches an off-by-one in the roll direction or writing x to the wrong tap.
static void check_two_steps(void) {
    // Independent numpy reference for two steps with the same weights.
    //   step1: state_a = roll(state0) + x0 ; out0 = silu((state_a * w).sum)
    //   step2: state_b = roll(state_a) + x1; out1 = silu((state_b * w).sum)
    // Hard-coded x1 + the resulting state_b / out1 below were produced by the
    // same numpy script (seed kept, second draw for x1).
    const float x1[8] = {
        0.5728960037231445f, 0.7658089995384216f, -1.228420615196228f, -0.8366431593894958f,
        -0.21271979808807373f, -0.0516231469810009f, 1.0186495780944824f, 0.6452329158782959f,
    };
    // Expected state after step 2 (numpy state_b, channel-major: (k,c) at c*kernel+k).
    const float state_b_expected[8 * 4] = {
        0.885799527f, 0.571287036f, -0.731974542f, 0.572896004f, 0.449657410f, 0.182596818f, -0.785962403f, 0.765809000f,
        0.729027450f, 0.506041169f, 0.568452001f, -1.228420615f, -0.090203181f, -0.272124112f, 1.372986913f, -0.836643159f,
        1.052329659f, 0.109724000f, -0.094989255f, -0.212719798f, -0.141164109f, -0.158164412f, -0.455060810f, -0.051623147f,
        0.198634371f, -0.742488980f, 0.293488562f, 1.018649578f, 1.192807198f, -0.185929254f, 0.259672523f, 0.645232916f,
    };
    // Expected out1 (numpy silu((state_b * w).sum(axis=1))).
    const float out1_expected[8] = {
        -0.050489295f, -0.035498492f, 0.583587646f, -0.237792537f, 0.342081100f, -0.090680420f, -0.046983868f, -0.001504717f,
    };

    float state[8 * 4];
    float out[8];
    std::memcpy(state, g_state_in, sizeof(state));

    nnml_ssm_conv1d_update(g_x_in, state, g_w_in, g_conv_dim, g_kernel, out);  // step 1 (discard out)
    nnml_ssm_conv1d_update(x1,        state, g_w_in, g_conv_dim, g_kernel, out);  // step 2

    for (int c = 0; c < g_conv_dim; ++c) {
        if (std::fabs(out[c] - out1_expected[c]) > 1e-5f) {
            printf("FAIL two-step out[%d]: got %.9f, expected %.9f\n", c, out[c], out1_expected[c]);
            ++g_fails;
        }
    }
    for (int i = 0; i < g_conv_dim * g_kernel; ++i) {
        if (std::fabs(state[i] - state_b_expected[i]) > 1e-5f) {
            printf("FAIL two-step state[%d]: got %.9f, expected %.9f\n", i, state[i], state_b_expected[i]);
            ++g_fails;
        }
    }
}

// Degenerate args must be a safe no-op (no crash, no write).
static void check_null_and_degenerate(void) {
    float state[4] = {1, 2, 3, 4};
    float out[4] = {9, 9, 9, 9};
    // null x -> no-op
    nnml_ssm_conv1d_update(nullptr, state, g_w_in, 4, 4, out);
    if (out[0] != 9.0f) { printf("FAIL null x wrote out\n"); ++g_fails; }
    // conv_dim 0 -> no-op
    nnml_ssm_conv1d_update(g_x_in, state, g_w_in, 0, 4, out);
    if (out[0] != 9.0f) { printf("FAIL conv_dim=0 wrote out\n"); ++g_fails; }
    // kernel 0 -> no-op (no taps; output undefined, must not touch it)
    nnml_ssm_conv1d_update(g_x_in, state, g_w_in, 4, 0, out);
    if (out[0] != 9.0f) { printf("FAIL kernel=0 wrote out\n"); ++g_fails; }
}

// ===========================================================================
// nnml_ssm_gated_delta_rule_update — gated delta-rule recurrent update for
// ONE head, ONE token (Qwen3.5 GatedDeltaNet linear attention).
//
// The expected output and expected new recurrent state were generated by an
// independent numpy reference (transformers/models/qwen3_5/modeling_qwen3_5.py
// torch_recurrent_gated_delta_rule, modeling_qwen3_5.py:404-443), collapsed to
// the per-head / single-token decode case and computed in float64:
//
//   def l2norm(x, eps=1e-6): return x / np.sqrt((x*x).sum() + eps)   # HF form
//   def step(q,k,v,g,beta,S,k_dim):
//       qn = l2norm(q) * (1/np.sqrt(k_dim)); kn = l2norm(k)
//       S  = S * np.exp(g)
//       kv_mem = S.T @ kn                 # [v_dim] = sum_k S[k,v]*kn[k]
//       delta  = (v - kv_mem) * beta
//       S  = S + np.outer(kn, delta)      # rank-1 update
//       out = S.T @ qn                    # [v_dim] = sum_k S[k,v]*qn[k]
//       return out, S
//
// Validates output AND the in-place recurrent-state mutation against HF, for
// both a single token and a 2-token sequence (state persistence).
// ===========================================================================

static const int g_kv_dim = 8;   // k_dim == v_dim for this test (math is dim-agnostic)

// Per-token scalars (numpy RandomState 20240728): g is raw (op applies exp(g)).
static const float g_g0    = 0.321360189f;
static const float g_beta0 = 0.985027477f;
static const float g_g1    = 0.285411045f;
static const float g_beta1 = 0.418184106f;

// Token-1 inputs (numpy RandomState 20240728).
static const float g_q0_in[8] = {
    -1.045677900f, -1.122803450f, 0.812074304f, 1.961409807f,
    -0.135698929f, -0.650086880f, 0.419269383f, 0.370960742f,
};
static const float g_k0_in[8] = {
    0.529839516f, 0.422582507f, 1.771599054f, 1.142574072f,
    -0.142246529f, 0.170401290f, 0.899314821f, 0.365193635f,
};
static const float g_v0_in[8] = {
    -0.996634185f, 0.093519822f, 1.458054900f, 1.012082338f,
    0.137399092f, 0.869541466f, -0.180406362f, -0.544248223f,
};
// Token-2 inputs (different q/k/v and different per-token g, beta).
static const float g_q1_in[8] = {
    -0.436527371f, 0.638733149f, 0.685346067f, 1.456057668f,
    0.660066605f, -0.298755020f, -1.587043524f, -1.240392327f,
};
static const float g_k1_in[8] = {
    -0.737963915f, -0.336787283f, -1.153220892f, -0.944742024f,
    -0.855937779f, 1.418806911f, 1.315191269f, 0.096383542f,
};
static const float g_v1_in[8] = {
    0.463362217f, 0.236999989f, 0.687077761f, 0.421574950f,
    -2.322186232f, 0.799521148f, -0.090307705f, 0.616687655f,
};
// Initial recurrent state S0 (row-major [k_dim, v_dim] = [8,8]).
static const float g_S0_in[64] = {
    1.943038583f, 0.113591574f, -1.666441798f, -0.967841387f,
    1.738613486f, -0.379163057f, -0.325081617f, 0.386729479f,
    -0.361426085f, -0.228145093f, 0.339344829f, 1.072094560f,
    0.210807174f, 1.291182637f, -0.171949506f, -0.010428713f,
    0.284762025f, -1.084678650f, 0.365374714f, -1.108275056f,
    0.658802688f, 0.213522866f, -0.430784792f, 0.654098809f,
    -0.988806784f, 1.453189492f, 0.114005014f, -0.391799480f,
    1.632812619f, -0.139974087f, 2.071068525f, 1.365647435f,
    0.955117881f, 0.834154725f, -1.492321610f, -0.864607036f,
    0.481279403f, 0.302769452f, 1.617540956f, 0.754963756f,
    0.799284995f, 0.917160630f, 0.435837835f, 1.661776543f,
    1.276557207f, 0.486050308f, -0.274972618f, -0.499734133f,
    0.526038289f, -1.092254758f, -2.400571108f, 0.978912294f,
    0.341122746f, -0.816312730f, 1.681313992f, -1.330051422f,
    -1.547605276f, 0.319895089f, 0.931545258f, 1.063248992f,
    1.018646836f, 0.192393348f, -0.693944037f, 0.987619281f,
};

// Expected output + recurrent state after token 1 (numpy step on S0).
static const float g_out0_expected[8] = {
    -0.939883149f, 0.303950208f, 0.569797783f, -0.122761873f,
    -0.188659320f, -0.170506045f, 0.580878197f, 0.244725834f,
};
static const float g_S1_expected[64] = {
    2.445718401f, 0.314136833f, -1.802179648f, -1.019906623f,
    1.832387323f, -0.328498432f, -0.772758527f, 0.185351430f,
    -0.684827534f, -0.189000725f, 0.863428659f, 1.729453979f,
    -0.160052983f, 1.935565391f, -0.495905518f, -0.291894148f,
    -0.388844649f, -0.969169738f, 2.161793259f, -0.475903313f,
    -0.981223121f, 0.944348339f, -1.678968884f, -0.261417977f,
    -1.867607589f, 2.343579498f, 1.226484501f, 0.138448627f,
    1.032901466f, 0.226121453f, 2.156303125f, 1.132894308f,
    1.379861001f, 1.108018681f, -2.191035365f, -1.276795907f,
    0.815415611f, 0.365337505f, 2.317703372f, 1.134510980f,
    1.027044079f, 1.315417984f, 0.760490392f, 2.392819613f,
    1.578613060f, 0.732775069f, -0.483540482f, -0.801038202f,
    0.328679697f, -1.238902061f, -2.468774248f, 1.884156108f,
    -0.488864094f, -0.795789127f, 1.767801148f, -2.424730251f,
    -2.295254424f, 0.549689152f, 1.626367304f, 1.683164321f,
    1.015174732f, 0.399279809f, -1.180592550f, 1.122103902f,
};

// Expected output + recurrent state after token 2 (numpy step on S1, sequential).
static const float g_out1_expected[8] = {
    -0.254384026f, 0.572834497f, 0.606524547f, -0.533980644f,
    0.148895957f, 0.348376359f, 0.413497350f, 0.419004193f,
};
static const float g_S2_expected[64] = {
    3.263621719f, 0.283755477f, -2.628781690f, -0.974616538f,
    2.693572812f, -0.639028827f, -1.007832987f, -0.157758201f,
    -0.906440395f, -0.312648871f, 1.043055428f, 2.475121942f,
    -0.096119281f, 2.482700889f, -0.650500363f, -0.572836182f,
    -0.501560775f, -1.498921857f, 2.514357273f, -0.035872367f,
    -0.905383198f, 0.940569885f, -2.202020258f, -0.979620093f,
    -2.471614365f, 2.945953657f, 1.335458835f, 0.673439084f,
    1.701722143f, 0.042179417f, 2.894376201f, 0.989471966f,
    1.847310732f, 1.318418716f, -3.183060604f, -1.255262708f,
    1.381600769f, 0.251690736f, 3.106660632f, 1.040278773f,
    1.346942133f, 2.007815860f, 1.456434293f, 2.448422110f,
    1.607988836f, 1.363228677f, -0.682045417f, -0.288259198f,
    0.419314559f, -1.409053152f, -2.871964608f, 1.825402711f,
    -1.106459321f, -0.698599369f, 2.315766654f, -2.505042257f,
    -3.054711068f, 0.748776412f, 2.193783561f, 2.189213427f,
    1.317069207f, 0.557551309f, -1.573187509f, 1.545553477f,
};

// f32 vs float64-reference tolerance: exp + contractions over the recurrent
// state accumulate a few ulps; 1e-4 is comfortable headroom (observed max ~1e-5).
static const float g_delta_tol = 1e-4f;

static void check_delta_rule_one_token(void) {
    float S[64];
    float out[8];
    std::memcpy(S, g_S0_in, sizeof(S));

    nnml_ssm_gated_delta_rule_update(g_q0_in, g_k0_in, g_v0_in,
                                     g_g0, g_beta0, S, g_kv_dim, g_kv_dim, out);

    for (int vv = 0; vv < g_kv_dim; ++vv) {
        if (std::fabs(out[vv] - g_out0_expected[vv]) > g_delta_tol) {
            printf("FAIL delta out0[%d]: got %.9f, expected %.9f\n",
                   vv, out[vv], g_out0_expected[vv]);
            ++g_fails;
        }
    }
    for (int i = 0; i < g_kv_dim * g_kv_dim; ++i) {
        if (std::fabs(S[i] - g_S1_expected[i]) > g_delta_tol) {
            printf("FAIL delta S1[%d]: got %.9f, expected %.9f\n",
                   i, S[i], g_S1_expected[i]);
            ++g_fails;
        }
    }
}

// Two consecutive updates: token 1 mutates S0 -> S1, token 2 mutates S1 -> S2.
// out1 and S2 are checked — this catches state-persistence bugs (e.g. reading
// pre-decay or pre-update S, or wrong contraction axes that only cancel on one
// step).
static void check_delta_rule_two_token(void) {
    float S[64];
    float out[8];
    std::memcpy(S, g_S0_in, sizeof(S));

    nnml_ssm_gated_delta_rule_update(g_q0_in, g_k0_in, g_v0_in,
                                     g_g0, g_beta0, S, g_kv_dim, g_kv_dim, out);  // step 1
    nnml_ssm_gated_delta_rule_update(g_q1_in, g_k1_in, g_v1_in,
                                     g_g1, g_beta1, S, g_kv_dim, g_kv_dim, out);  // step 2

    for (int vv = 0; vv < g_kv_dim; ++vv) {
        if (std::fabs(out[vv] - g_out1_expected[vv]) > g_delta_tol) {
            printf("FAIL delta out1[%d]: got %.9f, expected %.9f\n",
                   vv, out[vv], g_out1_expected[vv]);
            ++g_fails;
        }
    }
    for (int i = 0; i < g_kv_dim * g_kv_dim; ++i) {
        if (std::fabs(S[i] - g_S2_expected[i]) > g_delta_tol) {
            printf("FAIL delta S2[%d]: got %.9f, expected %.9f\n",
                   i, S[i], g_S2_expected[i]);
            ++g_fails;
        }
    }
}

// Degenerate args must be a safe no-op for the delta rule too (no crash/write).
static void check_delta_rule_null_and_degenerate(void) {
    float S[4] = {1, 2, 3, 4};
    float out[4] = {9, 9, 9, 9};
    nnml_ssm_gated_delta_rule_update(nullptr, g_k0_in, g_v0_in, 0.0f, 0.5f, S, 4, 4, out);
    if (out[0] != 9.0f) { printf("FAIL delta null q wrote out\n"); ++g_fails; }
    nnml_ssm_gated_delta_rule_update(g_q0_in, g_k0_in, g_v0_in, 0.0f, 0.5f, nullptr, 4, 4, out);
    if (out[0] != 9.0f) { printf("FAIL delta null S wrote out\n"); ++g_fails; }
    nnml_ssm_gated_delta_rule_update(g_q0_in, g_k0_in, g_v0_in, 0.0f, 0.5f, S, 0, 4, out);
    if (out[0] != 9.0f) { printf("FAIL delta k_dim=0 wrote out\n"); ++g_fails; }
    nnml_ssm_gated_delta_rule_update(g_q0_in, g_k0_in, g_v0_in, 0.0f, 0.5f, S, 4, 0, out);
    if (out[0] != 9.0f) { printf("FAIL delta v_dim=0 wrote out\n"); ++g_fails; }
}

// ===========================================================================
// nnml_ssm_rms_norm_gated — gated RMSNorm for Qwen3.5 GatedDeltaNet output.
//
// Expected output generated by an independent numpy reference matching HF's
// Qwen3_5RMSNormGated.forward (modeling_qwen3_5.py:271-280), computed in
// float64:
//
//   def silu(v): return v / (1.0 + np.exp(-v))
//   var = (x*x).mean()
//   out = weight * (x * (1.0/np.sqrt(var + 1e-6))) * silu(gate)
//
// Inputs use numpy RandomState 20240728 (continuing the same stream as the
// conv1d test). Tolerance 1e-6: only a few ulps of f32 vs float64 drift.
// ===========================================================================

static const int g_norm_n = 8;
static const float g_norm_x[8] = {
    -0.7319745421409607f, -0.7859624028205872f, 0.568452000617981f, 1.372986912727356f,
    -0.09498925507068634f, -0.45506080985069275f, 0.2934885621070862f, 0.25967252254486084f,
};
static const float g_norm_w[8] = {
    1.1589518785476685f, 1.126774787902832f, 1.5314797163009644f, 1.3427722454071045f,
    0.9573260545730591f, 1.051120400428772f, 1.2697944641113281f, 1.10955810546875f,
};
static const float g_norm_gate[8] = {
    -0.49831709265708923f, 0.04675991088151932f, 0.7290274500846863f, 0.5060411691665649f,
    0.06869954615831375f, 0.43477073311805725f, -0.0902031809091568f, -0.27212411165237427f,
};
static const float g_norm_out_expected[8] = {
    0.23393380641937256f, -0.03102594055235386f, 0.6268985867500305f, 0.8522392511367798f,
    -0.0047307200729846954f, -0.18483617901802063f, -0.023501459509134293f, -0.04963884502649307f,
};

static void check_rms_norm_gated(void) {
    float out[8];
    nnml_ssm_rms_norm_gated(g_norm_x, g_norm_w, g_norm_gate, g_norm_n, 1e-6f, out);
    for (int i = 0; i < g_norm_n; ++i) {
        if (std::fabs(out[i] - g_norm_out_expected[i]) > 1e-6f) {
            printf("FAIL rms_norm_gated[%d]: got %.9f, expected %.9f\n",
                   i, out[i], g_norm_out_expected[i]);
            ++g_fails;
        }
    }
}

// In-place aliasing: out == x must work (norm writes from double-buffered
// per-element math, so x is fully consumed before out[i] is written).
static void check_rms_norm_gated_inplace(void) {
    float buf[8];
    std::memcpy(buf, g_norm_x, sizeof(buf));
    nnml_ssm_rms_norm_gated(buf, g_norm_w, g_norm_gate, g_norm_n, 1e-6f, buf);
    for (int i = 0; i < g_norm_n; ++i) {
        if (std::fabs(buf[i] - g_norm_out_expected[i]) > 1e-6f) {
            printf("FAIL rms_norm_gated inplace[%d]: got %.9f, expected %.9f\n",
                   i, buf[i], g_norm_out_expected[i]);
            ++g_fails;
        }
    }
}

static void check_rms_norm_gated_null_and_degenerate(void) {
    float out[4] = {9, 9, 9, 9};
    nnml_ssm_rms_norm_gated(nullptr, g_norm_w, g_norm_gate, 4, 1e-6f, out);
    if (out[0] != 9.0f) { printf("FAIL rms_norm null x wrote out\n"); ++g_fails; }
    nnml_ssm_rms_norm_gated(g_norm_x, g_norm_w, g_norm_gate, 0, 1e-6f, out);
    if (out[0] != 9.0f) { printf("FAIL rms_norm n=0 wrote out\n"); ++g_fails; }
}

// ===========================================================================
// nnml_qwen35_partial_rotary — partial-rotary mRoPE for ONE head, ONE token
// (Qwen3.5 full-attention layers).
//
// Expected output generated two ways and cross-checked:
//   (a) HF apply_rotary_pos_emb (modeling_qwen3_5.py:638-673) with cos/sin
//       built by Qwen3_5TextRotaryEmbedding for a single text position;
//   (b) an independent numpy re-implementation of the documented convention.
//   (a) and (b) agree to 1.2e-7 (f32 precision).
//
// Uses compact dims (head_dim=16, rotary_dim=8) — the rotation math is
// dim-agnostic, and the compact case still exercises: 4 rotated pairs, the
// rotate_half split, and 8 pass-through dims. pos=7, theta=1e7.
//   inv_freq[j] = 1/(theta^(2j/rotary_dim))  j in [0, 4)
//     = [1.0, 0.017782794, 3.1622779e-04, 5.6234135e-06]
// ===========================================================================

static const int  g_pr_head_dim   = 16;
static const int  g_pr_rotary_dim = 8;
static const float g_pr_theta      = 1.0e7f;
static const float g_pr_pos        = 7.0f;
static const float g_pr_q_in[16] = {
    0.16068010032176971f, 0.9715192914009094f, 1.052329659461975f, 0.1097240000963211f,
    0.5461364984512329f, -0.14004598557949066f, -0.14116410911083221f, -0.15816441178321838f,
    0.32755008339881897f, 0.1522490680217743f, 0.19863437116146088f, -0.7424889802932739f,
    -0.06564218550920486f, 0.5532870292663574f, 1.1928071975708008f, -0.18592925369739532f,
};
static const float g_pr_q_out_expected[16] = {
    -0.2376672625541687f, 0.9813899397850037f, 1.0526394844055176f, 0.10973022878170013f,
    0.5172982215881348f, -0.018340155482292175f, -0.13883434236049652f, -0.15816009044647217f,
    0.32755008339881897f, 0.1522490680217743f, 0.19863437116146088f, -0.7424889802932739f,
    -0.06564218550920486f, 0.5532870292663574f, 1.1928071975708008f, -0.18592925369739532f,
};

static void check_partial_rotary(void) {
    float out[16];
    nnml_qwen35_partial_rotary(g_pr_q_in, g_pr_pos, g_pr_head_dim,
                               g_pr_rotary_dim, g_pr_theta, out);
    // Rotated + pass-through must both match HF.
    for (int i = 0; i < g_pr_head_dim; ++i) {
        if (std::fabs(out[i] - g_pr_q_out_expected[i]) > 1e-6f) {
            printf("FAIL partial_rotary[%d]: got %.9f, expected %.9f\n",
                   i, out[i], g_pr_q_out_expected[i]);
            ++g_fails;
        }
    }
}

// In-place aliasing: q_out == q_in must work (the per-pair math reads both
// sources into locals before writing, so an alias is safe).
static void check_partial_rotary_inplace(void) {
    float buf[16];
    std::memcpy(buf, g_pr_q_in, sizeof(buf));
    nnml_qwen35_partial_rotary(buf, g_pr_pos, g_pr_head_dim,
                               g_pr_rotary_dim, g_pr_theta, buf);
    for (int i = 0; i < g_pr_head_dim; ++i) {
        if (std::fabs(buf[i] - g_pr_q_out_expected[i]) > 1e-6f) {
            printf("FAIL partial_rotary inplace[%d]: got %.9f, expected %.9f\n",
                   i, buf[i], g_pr_q_out_expected[i]);
            ++g_fails;
        }
    }
}

// pos=0 is a no-op rotation (cos=1, sin=0) -> output must equal input.
static void check_partial_rotary_zero_pos(void) {
    float out[16];
    nnml_qwen35_partial_rotary(g_pr_q_in, 0.0f, g_pr_head_dim,
                               g_pr_rotary_dim, g_pr_theta, out);
    for (int i = 0; i < g_pr_head_dim; ++i) {
        if (std::fabs(out[i] - g_pr_q_in[i]) > 1e-6f) {
            printf("FAIL partial_rotary pos=0[%d]: got %.9f, expected %.9f\n",
                   i, out[i], g_pr_q_in[i]);
            ++g_fails;
        }
    }
}

// rotary_dim=0 degenerates to a copy (no rotation anywhere).
static void check_partial_rotary_zero_rotary(void) {
    float out[16] = {9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9};
    nnml_qwen35_partial_rotary(g_pr_q_in, g_pr_pos, g_pr_head_dim, 0, g_pr_theta, out);
    for (int i = 0; i < g_pr_head_dim; ++i) {
        if (std::fabs(out[i] - g_pr_q_in[i]) > 1e-6f) {
            printf("FAIL partial_rotary rotary=0[%d]: got %.9f, expected %.9f\n",
                   i, out[i], g_pr_q_in[i]);
            ++g_fails;
        }
    }
}

static void check_partial_rotary_null_and_degenerate(void) {
    float out[4] = {9, 9, 9, 9};
    nnml_qwen35_partial_rotary(nullptr, g_pr_pos, 4, 4, g_pr_theta, out);
    if (out[0] != 9.0f) { printf("FAIL partial_rotary null q wrote out\n"); ++g_fails; }
    nnml_qwen35_partial_rotary(g_pr_q_in, g_pr_pos, 0, 0, g_pr_theta, out);
    if (out[0] != 9.0f) { printf("FAIL partial_rotary head_dim=0 wrote out\n"); ++g_fails; }
}

// ===========================================================================
// Graph-op integration: prove the side-effecting-op + persistent-state
// mechanism works end-to-end through the scheduler dispatch.
//
// For each new op (nnml_ssm_conv_update, nnml_ssm_delta_update) we build the
// node, run it via nnml_compute_node for "token 0", then re-run the SAME node
// for "token 1" (mirroring how process_ubatch recomputes the graph each token),
// and assert: (a) the node's output matches the standalone primitive for each
// token; (b) the PERSISTENT src tensor (conv_state / recurrent_state, allocated
// as NNML_TENSOR_TYPE_KVCACHE) is mutated correctly across both tokens,
// matching a 2-call standalone reference. This is exactly the property the
// decode path relies on: the graph is rebuilt per ubatch while the KV-resident
// recurrent state survives and is read-modify-written each step.
// ===========================================================================

// A small persistent memory pool: elastic KV buffer (grows on demand) so we do
// not have to size the recurrent state precisely; weight + activation buffers
// are generously pre-sized for the tiny test tensors.
static nnml_memory_t make_graph_test_mem(void) {
    nnml_memory::cparams mp;
    mp.total_wsize_bytes   = (std::size_t) 1 << 20;   // 1 MiB
    mp.total_csize_bytes   = (std::size_t) 1 << 20;
    mp.total_kvsize_bytes  = (std::size_t) 1 << 16;   // 64 KiB (elastic)
    mp.tmp_work_size_bytes = (std::size_t) 1 << 16;
    mp.is_kv_elastic       = true;
    mp.zero_init           = true;
    return nnml_memory::create(mp);
}

// Single-threaded compute state for driving nnml_compute_node directly.
static nnml_compute_state make_compute_state(void) {
    nnml_compute_state st{};
    st.ith = 0;
    st.nth = 1;
    return st;
}

// nnml_ssm_conv_update: 2-token conv-state persistence through the graph.
//
// Reuses the conv1d fixtures (g_x_in / g_state_in / g_w_in / g_out_expected /
// g_state_expected and the two-step x1 / out1_expected / state_b_expected) so
// the graph-op result is checked against the SAME numpy reference as the
// standalone primitive.
static const float g_x1_in[8] = {
    0.5728960037231445f, 0.7658089995384216f, -1.228420615196228f, -0.8366431593894958f,
    -0.21271979808807373f, -0.0516231469810009f, 1.0186495780944824f, 0.6452329158785959f,
};

static void check_graph_conv_update(nnml_memory_t & mem) {
    const int conv_dim = g_conv_dim;   // 8
    const int kernel   = g_kernel;     // 4

    // x: per-token activation. conv_state: PERSISTENT KV tensor ([kernel, conv_dim]).
    // weight: depthwise conv weight (same layout as conv_state).
    nnml_tensor * x      = tensor_new_1d(mem, NNML_TENSOR_TYPE_ACTIVATION, 0, 0, NNML_TYPE_F32, conv_dim);
    nnml_tensor * cstate = tensor_new_2d(mem, NNML_TENSOR_TYPE_KVCACHE,    0, 0, NNML_TYPE_F32, kernel, conv_dim);
    nnml_tensor * weight = tensor_new_2d(mem, NNML_TENSOR_TYPE_WEIGHT,     0, 0, NNML_TYPE_F32, kernel, conv_dim);
    std::memcpy(weight->tensor_data(), g_w_in, sizeof(g_w_in));

    // Initialize the persistent conv_state to the SAME starting state as the
    // standalone reference (so the two are directly comparable).
    std::memcpy(cstate->tensor_data(), g_state_in, sizeof(g_state_in));

    // Build the side-effecting graph node: out = ssm_conv_update(x, cstate, w).
    nnml_tensor * node = nnml_ssm_conv_update(mem, NNML_TENSOR_TYPE_ACTIVATION, 0, 0, x, cstate, weight);

    // Standalone 2-token reference (mutates ref_state in place). After token 0
    // it equals g_state_expected; after token 1 it is the 2-step rolled state.
    float ref_state[8 * 4];
    float ref_out0[8], ref_out1[8];
    std::memcpy(ref_state, g_state_in, sizeof(ref_state));
    nnml_ssm_conv1d_update(g_x_in,  ref_state, g_w_in, conv_dim, kernel, ref_out0);
    nnml_ssm_conv1d_update(g_x1_in, ref_state, g_w_in, conv_dim, kernel, ref_out1);
    // ref_state is now the state after BOTH standalone calls (2-step reference).

    nnml_compute_state st = make_compute_state();

    // --- token 0: feed x0, run the node through the scheduler dispatch. ---
    std::memcpy(x->tensor_data(), g_x_in, sizeof(g_x_in));
    nnml_compute_node(node, &st);
    const float * out0 = (const float *) node->tensor_data();
    const float * cs0  = (const float *) cstate->tensor_data();
    for (int c = 0; c < conv_dim; ++c) {
        if (std::fabs(out0[c] - ref_out0[c]) > 1e-5f) {
            printf("FAIL graph_conv out0[%d]: got %.9f, expected %.9f\n", c, out0[c], ref_out0[c]);
            ++g_fails;
        }
    }
    // Persistent conv_state must have been mutated to the rolled state.
    for (int i = 0; i < conv_dim * kernel; ++i) {
        if (std::fabs(cs0[i] - g_state_expected[i]) > 1e-5f) {
            printf("FAIL graph_conv state0[%d]: got %.9f, expected %.9f\n", i, cs0[i], g_state_expected[i]);
            ++g_fails;
        }
    }

    // --- token 1: re-run the SAME node with new input; state carries over. ---
    std::memcpy(x->tensor_data(), g_x1_in, sizeof(g_x1_in));
    nnml_compute_node(node, &st);
    const float * out1 = (const float *) node->tensor_data();
    const float * cs1  = (const float *) cstate->tensor_data();
    for (int c = 0; c < conv_dim; ++c) {
        if (std::fabs(out1[c] - ref_out1[c]) > 1e-5f) {
            printf("FAIL graph_conv out1[%d]: got %.9f, expected %.9f\n", c, out1[c], ref_out1[c]);
            ++g_fails;
        }
    }
    for (int i = 0; i < conv_dim * kernel; ++i) {
        if (std::fabs(cs1[i] - ref_state[i]) > 1e-5f) {
            printf("FAIL graph_conv state1[%d]: got %.9f, expected %.9f\n", i, cs1[i], ref_state[i]);
            ++g_fails;
        }
    }
}

// nnml_ssm_delta_update: 2-token recurrent-state persistence, looping 2 heads.
//
// head 0 starts from g_S0_in (non-zero); head 1 starts from ZERO state but
// receives the SAME per-token inputs as head 0. Because their initial states
// differ, their outputs differ — so any per-head stride bug (head 1 reading or
// writing head 0's S / out slice) shows up as a mismatch. head 1's reference is
// computed by calling the (already-validated) standalone primitive on a zero
// initial state. Both heads' graph output + mutated recurrent_state are checked
// against their references for token 0 and token 1.
static void check_graph_delta_update(nnml_memory_t & mem) {
    const int k_dim = g_kv_dim;     // 8
    const int v_dim = g_kv_dim;     // 8
    const int num_heads = 2;

    // Per-head-strided inputs: [k_dim, num_heads] for q/k, [v_dim, num_heads] for v.
    nnml_tensor * q    = tensor_new_2d(mem, NNML_TENSOR_TYPE_ACTIVATION, 0, 0, NNML_TYPE_F32, k_dim, num_heads);
    nnml_tensor * k    = tensor_new_2d(mem, NNML_TENSOR_TYPE_ACTIVATION, 0, 0, NNML_TYPE_F32, k_dim, num_heads);
    nnml_tensor * v    = tensor_new_2d(mem, NNML_TENSOR_TYPE_ACTIVATION, 0, 0, NNML_TYPE_F32, v_dim, num_heads);
    nnml_tensor * g    = tensor_new_1d(mem, NNML_TENSOR_TYPE_ACTIVATION, 0, 0, NNML_TYPE_F32, num_heads);
    nnml_tensor * beta = tensor_new_1d(mem, NNML_TENSOR_TYPE_ACTIVATION, 0, 0, NNML_TYPE_F32, num_heads);
    // Persistent recurrent state: [v_dim, k_dim, num_heads] KV tensor.
    nnml_tensor * rstate = tensor_new_3d(mem, NNML_TENSOR_TYPE_KVCACHE, 0, 0, NNML_TYPE_F32, v_dim, k_dim, num_heads);

    // head 0 initial S = g_S0_in; head 1 initial S = zeros.
    float * Sd = (float *) rstate->tensor_data();
    std::memcpy(Sd, g_S0_in, sizeof(g_S0_in));                      // head 0 (offset 0)
    std::memset(Sd + k_dim * v_dim, 0, sizeof(float) * k_dim * v_dim);  // head 1 (offset 64)

    // head 1 standalone reference (continues from the SAME zero initial state).
    float h1_S[64];
    std::memset(h1_S, 0, sizeof(h1_S));
    float h1_out0[8], h1_out1[8];
    // (head 0 reference is the existing g_out0/g_out1/g_S1/g_S2 expected arrays.)

    nnml_tensor * node = nnml_ssm_delta_update(mem, NNML_TENSOR_TYPE_ACTIVATION, 0, 0,
                                               q, k, v, g, beta, rstate);

    nnml_compute_state st = make_compute_state();

    // helper to load per-head inputs (head 1 mirrors head 0's inputs).
    auto load_token_inputs = [&](const float qh0[8], const float kh0[8], const float vh0[8],
                                 float gg, float bb) {
        float * qd = (float *) q->tensor_data();
        float * kd = (float *) k->tensor_data();
        float * vd = (float *) v->tensor_data();
        std::memcpy(qd + 0 * k_dim, qh0, sizeof(float) * k_dim);   // head 0
        std::memcpy(qd + 1 * k_dim, qh0, sizeof(float) * k_dim);   // head 1 = head 0
        std::memcpy(kd + 0 * k_dim, kh0, sizeof(float) * k_dim);
        std::memcpy(kd + 1 * k_dim, kh0, sizeof(float) * k_dim);
        std::memcpy(vd + 0 * v_dim, vh0, sizeof(float) * v_dim);
        std::memcpy(vd + 1 * v_dim, vh0, sizeof(float) * v_dim);
        ((float *) g->tensor_data())[0] = gg;
        ((float *) g->tensor_data())[1] = gg;
        ((float *) beta->tensor_data())[0] = bb;
        ((float *) beta->tensor_data())[1] = bb;
    };

    // --- token 0 ---
    load_token_inputs(g_q0_in, g_k0_in, g_v0_in, g_g0, g_beta0);
    nnml_compute_node(node, &st);
    nnml_ssm_gated_delta_rule_update(g_q0_in, g_k0_in, g_v0_in, g_g0, g_beta0, h1_S, g_kv_dim, g_kv_dim, h1_out0);  // head 1 ref (from zero S)

    const float * out0 = (const float *) node->tensor_data();
    for (int vv = 0; vv < v_dim; ++vv) {
        if (std::fabs(out0[vv] - g_out0_expected[vv]) > g_delta_tol) {
            printf("FAIL graph_delta out0 head0[%d]: got %.9f, expected %.9f\n", vv, out0[vv], g_out0_expected[vv]);
            ++g_fails;
        }
        if (std::fabs(out0[v_dim + vv] - h1_out0[vv]) > g_delta_tol) {
            printf("FAIL graph_delta out0 head1[%d]: got %.9f, expected %.9f\n", vv, out0[v_dim + vv], h1_out0[vv]);
            ++g_fails;
        }
    }
    // recurrent_state after token 0: head 0 == g_S1_expected, head 1 == h1_S.
    for (int i = 0; i < k_dim * v_dim; ++i) {
        if (std::fabs(Sd[i] - g_S1_expected[i]) > g_delta_tol) {
            printf("FAIL graph_delta S0 head0[%d]: got %.9f, expected %.9f\n", i, Sd[i], g_S1_expected[i]);
            ++g_fails;
        }
        if (std::fabs(Sd[k_dim * v_dim + i] - h1_S[i]) > g_delta_tol) {
            printf("FAIL graph_delta S0 head1[%d]: got %.9f, expected %.9f\n", i, Sd[k_dim * v_dim + i], h1_S[i]);
            ++g_fails;
        }
    }

    // --- token 1 ---
    load_token_inputs(g_q1_in, g_k1_in, g_v1_in, g_g1, g_beta1);
    nnml_compute_node(node, &st);
    nnml_ssm_gated_delta_rule_update(g_q1_in, g_k1_in, g_v1_in, g_g1, g_beta1, h1_S, g_kv_dim, g_kv_dim, h1_out1);  // head 1 ref (continued)

    const float * out1 = (const float *) node->tensor_data();
    for (int vv = 0; vv < v_dim; ++vv) {
        if (std::fabs(out1[vv] - g_out1_expected[vv]) > g_delta_tol) {
            printf("FAIL graph_delta out1 head0[%d]: got %.9f, expected %.9f\n", vv, out1[vv], g_out1_expected[vv]);
            ++g_fails;
        }
        if (std::fabs(out1[v_dim + vv] - h1_out1[vv]) > g_delta_tol) {
            printf("FAIL graph_delta out1 head1[%d]: got %.9f, expected %.9f\n", vv, out1[v_dim + vv], h1_out1[vv]);
            ++g_fails;
        }
    }
    for (int i = 0; i < k_dim * v_dim; ++i) {
        if (std::fabs(Sd[i] - g_S2_expected[i]) > g_delta_tol) {
            printf("FAIL graph_delta S1 head0[%d]: got %.9f, expected %.9f\n", i, Sd[i], g_S2_expected[i]);
            ++g_fails;
        }
        if (std::fabs(Sd[k_dim * v_dim + i] - h1_S[i]) > g_delta_tol) {
            printf("FAIL graph_delta S1 head1[%d]: got %.9f, expected %.9f\n", i, Sd[k_dim * v_dim + i], h1_S[i]);
            ++g_fails;
        }
    }
}

static void check_graph_ops(void) {
    nnml_memory_t mem = make_graph_test_mem();
    check_graph_conv_update(mem);
    check_graph_delta_update(mem);
}

// Multi-token conv: process 4 distinct tokens in one seq call; each token's output
// must equal running the (numpy-validated) single-token primitive sequentially with
// the rolling conv_state carried between steps (compositional validation).
static void check_conv_seq(void) {
    const int cd = g_conv_dim, k = g_kernel, T = 4;
    const float xs[4][8] = {
        { -0.731974542f, -0.785962403f,  0.568452001f,  1.372986913f, -0.094989255f, -0.455060810f,  0.293488562f,  0.259672523f },
        {  0.572896004f,  0.765809000f, -1.228420615f, -0.836643159f, -0.212719798f, -0.051623147f,  1.018649578f,  0.645232916f },
        {  0.300000012f, -0.400000006f,  0.899999976f, -0.200000003f,  0.600000024f, -0.699999988f,  0.100000001f,  0.500000000f },
        { -0.800000012f,  0.200000003f, -0.500000000f,  1.100000024f,  0.300000012f, -0.600000024f,  0.400000015f, -0.899999976f },
    };
    float xbuf[4][8];
    for (int t = 0; t < T; ++t)
        for (int c = 0; c < cd; ++c) xbuf[t][c] = xs[t][c];

    // Reference: sequential single-token calls with state carry.
    float state_ref[8 * 4];
    float out_ref[4][8];
    std::memcpy(state_ref, g_state_in, sizeof(state_ref));
    for (int t = 0; t < T; ++t)
        nnml_ssm_conv1d_update(xs[t], state_ref, g_w_in, cd, k, out_ref[t]);

    // Seq wrapper: token-major input, token stride = cd floats.
    float state_seq[8 * 4];
    float out_seq[4][8];
    std::memcpy(state_seq, g_state_in, sizeof(state_seq));
    nnml_ssm_conv1d_update_seq(&xbuf[0][0], cd * sizeof(float), state_seq, g_w_in,
                               cd, k, T, &out_seq[0][0], cd * sizeof(float), 0, 1);

    for (int t = 0; t < T; ++t)
        for (int c = 0; c < cd; ++c)
            if (std::fabs(out_seq[t][c] - out_ref[t][c]) > 1e-5f) {
                printf("FAIL conv_seq out[t=%d,c=%d]: got %.9f, expected %.9f\n", t, c, out_seq[t][c], out_ref[t][c]);
                ++g_fails;
            }
    for (int i = 0; i < cd * k; ++i)
        if (std::fabs(state_seq[i] - state_ref[i]) > 1e-5f) {
            printf("FAIL conv_seq state[%d]: got %.9f, expected %.9f\n", i, state_seq[i], state_ref[i]);
            ++g_fails;
        }
}

// Multi-token + multi-head delta seq: validates the seq wrapper against the
// numpy-validated single-token fixtures. (a) 2 tokens, 1 head == the existing
// two-token reference (g_out1/g_S2_expected). (b) 1 token, 2 heads (head1 an
// independent copy of head0) == the single-token result, exercising the head loop.
static void check_delta_seq(void) {
    const int KD = g_kv_dim, VD = g_kv_dim;   // 8

    // (a) 2 tokens, 1 head: q/k/v [KD,1,2], g/beta [1,2].
    float q2[16], k2[16], v2[16];
    float g2[2] = { g_g0, g_g1 };
    float b2[2] = { g_beta0, g_beta1 };
    std::memcpy(q2, g_q0_in, 8 * sizeof(float)); std::memcpy(q2 + 8, g_q1_in, 8 * sizeof(float));
    std::memcpy(k2, g_k0_in, 8 * sizeof(float)); std::memcpy(k2 + 8, g_k1_in, 8 * sizeof(float));
    std::memcpy(v2, g_v0_in, 8 * sizeof(float)); std::memcpy(v2 + 8, g_v1_in, 8 * sizeof(float));
    float S[64]; std::memcpy(S, g_S0_in, sizeof(S));
    float out[16];
    nnml_ssm_delta_rule_update_seq(q2, KD * sizeof(float), k2, KD * sizeof(float),
                                   v2, VD * sizeof(float), g2, sizeof(float),
                                   b2, sizeof(float), S, KD, VD, 1, 2,
                                   out, VD * sizeof(float), 0, 1);
    for (int vv = 0; vv < VD; ++vv)
        if (std::fabs(out[8 + vv] - g_out1_expected[vv]) > g_delta_tol) {
            printf("FAIL delta_seq out1[%d]: got %.9f, expected %.9f\n", vv, out[8 + vv], g_out1_expected[vv]);
            ++g_fails;
        }
    for (int i = 0; i < KD * VD; ++i)
        if (std::fabs(S[i] - g_S2_expected[i]) > g_delta_tol) {
            printf("FAIL delta_seq S2[%d]: got %.9f, expected %.9f\n", i, S[i], g_S2_expected[i]);
            ++g_fails;
        }

    // (b) 1 token, 2 heads: q/k/v [KD,2,1], g/beta [2,1]. head1 = copy of head0.
    float qh[16], kh[16], vh[16];
    float gh[2] = { g_g0, g_g0 };
    float bh[2] = { g_beta0, g_beta0 };
    std::memcpy(qh,     g_q0_in, 8 * sizeof(float)); std::memcpy(qh + 8,     g_q0_in, 8 * sizeof(float));
    std::memcpy(kh,     g_k0_in, 8 * sizeof(float)); std::memcpy(kh + 8,     g_k0_in, 8 * sizeof(float));
    std::memcpy(vh,     g_v0_in, 8 * sizeof(float)); std::memcpy(vh + 8,     g_v0_in, 8 * sizeof(float));
    float S2[128];
    std::memcpy(S2,       g_S0_in, 64 * sizeof(float));
    std::memcpy(S2 + 64,  g_S0_in, 64 * sizeof(float));
    float outh[16];
    nnml_ssm_delta_rule_update_seq(qh, KD * 2 * sizeof(float), kh, KD * 2 * sizeof(float),
                                   vh, VD * 2 * sizeof(float), gh, 2 * sizeof(float),
                                   bh, 2 * sizeof(float), S2, KD, VD, 2, 1,
                                   outh, VD * 2 * sizeof(float), 0, 1);
    for (int h = 0; h < 2; ++h)
        for (int vv = 0; vv < VD; ++vv)
            if (std::fabs(outh[h * 8 + vv] - g_out0_expected[vv]) > g_delta_tol) {
                printf("FAIL delta_seq head%d out0[%d]: got %.9f, expected %.9f\n", h, vv, outh[h * 8 + vv], g_out0_expected[vv]);
                ++g_fails;
            }
}

int main(void) {
    check_main_update();
    check_two_steps();
    check_conv_seq();
    check_null_and_degenerate();
    check_delta_rule_one_token();
    check_delta_rule_two_token();
    check_delta_seq();
    check_delta_rule_null_and_degenerate();
    check_rms_norm_gated();
    check_rms_norm_gated_inplace();
    check_rms_norm_gated_null_and_degenerate();
    check_partial_rotary();
    check_partial_rotary_inplace();
    check_partial_rotary_zero_pos();
    check_partial_rotary_zero_rotary();
    check_partial_rotary_null_and_degenerate();
    check_graph_ops();

    if (g_fails == 0) {
        printf("test-ssm: PASS (conv1d_update + delta_rule + rms_norm_gated + "
               "partial_rotary == numpy/HF reference; ssm graph ops mutate state "
               "across 2 tokens, match standalone)\n");
        return 0;
    }
    printf("test-ssm: FAIL (%d assertions)\n", g_fails);
    return 1;
}
